eureka:
  client:
    initialInstanceInfoReplicationIntervalSeconds: 40
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh
